export const fitnessData = {
  January: {
    workoutFrequency: 12,
    workoutsThisMonth: 12,
    currentStreak: 5,
    totalVolumeLifted: 18500, // in kg
    activeThisWeek: 3,
  },
  February: {
    workoutFrequency: 10,
    workoutsThisMonth: 10,
    currentStreak: 4,
    totalVolumeLifted: 16200,
    activeThisWeek: 2,
  },
  March: {
    workoutFrequency: 14,
    workoutsThisMonth: 14,
    currentStreak: 7,
    totalVolumeLifted: 21000,
    activeThisWeek: 4,
  },
  April: {
    workoutFrequency: 11,
    workoutsThisMonth: 11,
    currentStreak: 3,
    totalVolumeLifted: 17000,
    activeThisWeek: 2,
  },
  May: {
    workoutFrequency: 15,
    workoutsThisMonth: 15,
    currentStreak: 8,
    totalVolumeLifted: 22500,
    activeThisWeek: 5,
  },
  June: {
    workoutFrequency: 13,
    workoutsThisMonth: 13,
    currentStreak: 6,
    totalVolumeLifted: 19500,
    activeThisWeek: 3,
  },
  July: {
    workoutFrequency: 16,
    workoutsThisMonth: 16,
    currentStreak: 9,
    totalVolumeLifted: 24000,
    activeThisWeek: 6,
  },
  August: {
    workoutFrequency: 15,
    workoutsThisMonth: 15,
    currentStreak: 10,
    totalVolumeLifted: 22500,
    activeThisWeek: 5,
  },
  September: {
    workoutFrequency: 14,
    workoutsThisMonth: 14,
    currentStreak: 7,
    totalVolumeLifted: 21000,
    activeThisWeek: 4,
  },
}
